services:
  postgres:
    image: 'postgres:15.3-alpine'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=secret'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - './datadir/postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - 'backend'
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=user@user.com'
      - 'PGADMIN_DEFAULT_PASSWORD=secret'
      - 'PGADMIN_LISTEN_PORT=5050'
    ports:
      - '5050:5050'
    networks:
      - 'backend'

networks:
  backend:
    driver: 'host'